"""
Report Generation - Creates PDF/HTML reports for teachers
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os
from typing import Dict
from analyze_student_data import StudentDataAnalyzer
from visualizations import DataVisualizer
import config


class ReportGenerator:
    """Generates comprehensive reports for teachers"""
    
    def __init__(self):
        """Initialize report generator"""
        self.analyzer = StudentDataAnalyzer(days=config.ANALYSIS_CONFIG['recent_days'])
        self.visualizer = DataVisualizer()
        self.styles = getSampleStyleSheet()
        
        # Create custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            fontName='Helvetica-Bold'
        )
        
        self.body_style = ParagraphStyle(
            'CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            alignment=TA_LEFT
        )
        
        # Ensure output directory exists
        os.makedirs(config.REPORT_CONFIG['output_dir'], exist_ok=True)
        os.makedirs(config.REPORT_CONFIG['charts_dir'], exist_ok=True)
    
    def create_pdf_report(self, output_filename: str = None) -> str:
        """
        Create comprehensive PDF report
        
        Args:
            output_filename: Output filename (auto-generated if None)
        
        Returns:
            Path to generated report
        """
        # Generate filename
        if not output_filename:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'socrates_report_{timestamp}.pdf'
        
        output_path = os.path.join(config.REPORT_CONFIG['output_dir'], output_filename)
        
        # Create document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )
        
        # Container for elements
        elements = []
        
        # Generate analysis data
        report_data = self.analyzer.generate_summary_report()
        
        # Generate visualizations
        print("Generating visualizations for report...")
        self.visualizer.generate_all_charts(days=config.ANALYSIS_CONFIG['recent_days'])
        
        # Title Page
        elements.append(Paragraph("Socrates AI", self.title_style))
        elements.append(Paragraph("Student Learning Analytics Report", self.heading_style))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Report metadata
        meta_data = [
            ['Report Date:', datetime.now().strftime('%B %d, %Y')],
            ['Analysis Period:', f'Last {config.ANALYSIS_CONFIG["recent_days"]} days'],
            ['Generated By:', 'Socrates AI Analytics Pipeline'],
        ]
        
        meta_table = Table(meta_data, colWidths=[2 * inch, 4 * inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#666666')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ]))
        
        elements.append(meta_table)
        elements.append(Spacer(1, 0.5 * inch))
        
        # Executive Summary
        elements.append(Paragraph("Executive Summary", self.heading_style))
        
        summary_text = f"""
        This report provides comprehensive insights into student learning patterns, 
        struggles, and engagement over the past {config.ANALYSIS_CONFIG['recent_days']} days. 
        The analysis covers {report_data['query_analysis']['unique_students']} students who 
        submitted {report_data['query_analysis']['total_queries']} queries to the AI tutor.
        """
        
        elements.append(Paragraph(summary_text, self.body_style))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Key Metrics Table
        elements.append(Paragraph("Key Metrics", self.heading_style))
        
        metrics_data = [
            ['Metric', 'Value'],
            ['Total Queries', str(report_data['query_analysis']['total_queries'])],
            ['Active Students', str(report_data['query_analysis']['unique_students'])],
            ['Average Queries per Student', f"{report_data['query_analysis']['avg_queries_per_student']:.2f}"],
            ['Total Struggles Logged', str(report_data['struggle_analysis']['total_struggles'])],
            ['Students with Struggles', str(report_data['struggle_analysis']['students_affected'])],
        ]
        
        metrics_table = Table(metrics_data, colWidths=[3 * inch, 2 * inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        
        elements.append(metrics_table)
        elements.append(PageBreak())
        
        # Struggle Analysis Section
        elements.append(Paragraph("Student Struggle Analysis", self.heading_style))
        
        if report_data['struggle_analysis']['top_topics']:
            struggle_text = "Students are encountering challenges in the following areas:"
            elements.append(Paragraph(struggle_text, self.body_style))
            elements.append(Spacer(1, 0.2 * inch))
            
            # Top struggles table
            struggle_data = [['Rank', 'Topic', 'Struggle Count']]
            for i, topic in enumerate(report_data['struggle_analysis']['top_topics'][:10], 1):
                struggle_data.append([str(i), topic['topic'], str(topic['count'])])
            
            struggle_table = Table(struggle_data, colWidths=[0.7 * inch, 3.5 * inch, 1.3 * inch])
            struggle_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e74c3c')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ]))
            
            elements.append(struggle_table)
            elements.append(Spacer(1, 0.3 * inch))
            
            # Add chart if available
            chart_path = os.path.join(config.REPORT_CONFIG['charts_dir'], 'struggle_topics.png')
            if os.path.exists(chart_path):
                elements.append(Image(chart_path, width=5.5 * inch, height=3.5 * inch))
        
        elements.append(PageBreak())
        
        # Query Activity Section
        elements.append(Paragraph("Query Activity Analysis", self.heading_style))
        
        activity_text = f"""
        Students are most active during specific times. The peak query hour is 
        {report_data['query_analysis']['peak_hours'][0]['hour']}:00 with 
        {report_data['query_analysis']['peak_hours'][0]['count']} queries.
        """
        
        elements.append(Paragraph(activity_text, self.body_style))
        elements.append(Spacer(1, 0.3 * inch))
        
        # Timeline chart
        timeline_path = os.path.join(config.REPORT_CONFIG['charts_dir'], 'query_timeline.png')
        if os.path.exists(timeline_path):
            elements.append(Image(timeline_path, width=5.5 * inch, height=3.5 * inch))
        
        elements.append(Spacer(1, 0.3 * inch))
        
        # Heatmap
        heatmap_path = os.path.join(config.REPORT_CONFIG['charts_dir'], 'activity_heatmap.png')
        if os.path.exists(heatmap_path):
            elements.append(Image(heatmap_path, width=6 * inch, height=3 * inch))
        
        elements.append(PageBreak())
        
        # Key Insights Section
        elements.append(Paragraph("Key Insights & Recommendations", self.heading_style))
        
        for i, insight in enumerate(report_data['insights'], 1):
            insight_text = f"{i}. {insight}"
            elements.append(Paragraph(insight_text, self.body_style))
            elements.append(Spacer(1, 0.1 * inch))
        
        # Build PDF
        doc.build(elements)
        
        print(f"\nPDF report generated: {output_path}")
        return output_path
    
    def create_summary_html(self, output_filename: str = None) -> str:
        """
        Create HTML summary report
        
        Args:
            output_filename: Output filename
        
        Returns:
            Path to generated HTML
        """
        if not output_filename:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'socrates_summary_{timestamp}.html'
        
        output_path = os.path.join(config.REPORT_CONFIG['output_dir'], output_filename)
        
        # Generate data
        report_data = self.analyzer.generate_summary_report()
        
        # Create HTML
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Socrates AI - Analytics Summary</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
                .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
                h1 {{ color: #2c3e50; text-align: center; }}
                h2 {{ color: #3498db; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                .metric {{ display: inline-block; margin: 20px; padding: 20px; background: #ecf0f1; border-radius: 8px; min-width: 200px; }}
                .metric-value {{ font-size: 32px; font-weight: bold; color: #2c3e50; }}
                .metric-label {{ font-size: 14px; color: #7f8c8d; margin-top: 5px; }}
                .insight {{ background: #fff3cd; padding: 15px; margin: 10px 0; border-left: 4px solid #ffc107; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th {{ background: #3498db; color: white; padding: 12px; text-align: left; }}
                td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
                tr:hover {{ background: #f5f5f5; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Socrates AI Analytics Summary</h1>
                <p style="text-align: center; color: #7f8c8d;">
                    Report Date: {datetime.now().strftime('%B %d, %Y')} | 
                    Period: Last {config.ANALYSIS_CONFIG['recent_days']} days
                </p>
                
                <h2>Key Metrics</h2>
                <div style="text-align: center;">
                    <div class="metric">
                        <div class="metric-value">{report_data['query_analysis']['total_queries']}</div>
                        <div class="metric-label">Total Queries</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">{report_data['query_analysis']['unique_students']}</div>
                        <div class="metric-label">Active Students</div>
                    </div>
                    <div class="metric">
                        <div class="metric-value">{report_data['struggle_analysis']['total_struggles']}</div>
                        <div class="metric-label">Total Struggles</div>
                    </div>
                </div>
                
                <h2>Top Struggling Topics</h2>
                <table>
                    <tr>
                        <th>Rank</th>
                        <th>Topic</th>
                        <th>Struggle Count</th>
                    </tr>
        """
        
        for i, topic in enumerate(report_data['struggle_analysis']['top_topics'][:10], 1):
            html_content += f"""
                    <tr>
                        <td>{i}</td>
                        <td>{topic['topic']}</td>
                        <td>{topic['count']}</td>
                    </tr>
            """
        
        html_content += """
                </table>
                
                <h2>Key Insights</h2>
        """
        
        for insight in report_data['insights']:
            html_content += f'<div class="insight">{insight}</div>\n'
        
        html_content += """
            </div>
        </body>
        </html>
        """
        
        with open(output_path, 'w') as f:
            f.write(html_content)
        
        print(f"HTML summary generated: {output_path}")
        return output_path


def main():
    """Main execution function"""
    print("=" * 60)
    print("SOCRATES AI - REPORT GENERATION")
    print("=" * 60)
    print()
    
    generator = ReportGenerator()
    
    # Generate PDF report
    print("Generating PDF report...")
    pdf_path = generator.create_pdf_report()
    
    # Generate HTML summary
    print("\nGenerating HTML summary...")
    html_path = generator.create_summary_html()
    
    print("\n" + "=" * 60)
    print("Report generation complete!")
    print(f"PDF: {pdf_path}")
    print(f"HTML: {html_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
